# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6313739aa1f2917d9e7515af96d436b7d419f46307e59ff432310775d145ce86cbfd699d881027e7a74441377f65ef2676d5d532ae7503383122b2b629058ea1

test:
  secret_key_base: eae6863267eeb41d4fe5a6a3822704462b61d2cd2fff8fe9ba160bf3985da1748a08197a8daed3ff5b852eff6391b5dac4498d049a58d957f2109e00084f52a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
